import { Providers } from '@/app/providers'
import { Footer } from '@/components/Footer'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ fontFamily: 'sans-serif' }}>
        <Providers>
          {children}

          <Footer />
        </Providers>
      </body>
    </html>
  )
}
